joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.2
    autorepeat_rate: 10.0
    coalesce_interval_ms: 50

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
      y: 0
    scale_linear:
      x: 0.2
      y: 0.2
    scale_linear_turbo:
      x: 0.5
      y: 0.5

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 2.0
    scale_angular_turbo:
      yaw: 4.0


    enable_button: 4
    enable_turbo_button: 5

    require_enable_button: true